/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
static yyconst short int yy_accept[397] =
    {   0,
        0,    0,   31,   29,   19,   30,   19,   29,   29,   28,
       18,   18,   24,   24,   24,   18,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   18,   18,   24,   19,
       19,    6,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   24,    0,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,    0,    0,
        0,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   18,   24,   24,   24,   24,   24,   24,    5,
        6,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   24,   24,   24,   24,   24,   24,   24,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,    0,    0,    0,    0,    0,    0,    0,
        0,   26,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   27,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   24,   24,

        0,   24,   17,   24,    0,    0,    0,    0,   11,    0,
        0,    0,    0,    0,    0,    0,    0,   24,   24,    0,
        0,    0,    0,    0,    0,   24,    0,   11,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   24,    0,   12,   13,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    3,    4,
        7,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   17,    0,
        0,    0,    0,    2,    0,    0,    0,    0,    0,    0,

        0,    9,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   16,    0,
        0,    0,    0,    0,   21,   25,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   14,    0,
       11,   15,    0,   22,    0,    0,    0,    0,   20,   23,
        0,    0,    0,    0,   10,    0,    0,    0,    1,    2,
        0,    0,    0,    0,    8,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    7,    8,    9,
       10,    1,   11,   12,   13,    1,    1,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,    1,    1,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   28,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    2,    3,    4,    4,    5,    6,    7,    1,    1,
        1,    8,    9,   10,   11,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13
    } ;

static yyconst short int yy_base[420] =
    {   0,
        0,    0, 1163, 1342, 1160, 1342,   39,    0,   27, 1342,
       56,   64,   68,   20,   49,   56,   21,   60,   61,   99,
       73,   95,   66,   79,   87,  108,  110,  120,  122, 1158,
       70, 1147,   34, 1121, 1120,  153,   89, 1094, 1084, 1086,
       88,   70, 1080,  143,  188, 1046,   80,  227,  132,  138,
      134,  139,  147,  159,  155,   86,  165,  196,  268,  307,
     1027,  170,  176,  177,  183,  330,  190,  205,  204,  188,
      244,  256,  198,  259,  210,  211,  149,  267,  265, 1342,
     1041, 1028, 1020, 1005,  989,  128,  313,  991,  983,  954,
      938,  354,  937,  919,  300,  303,  925,  902,  279,  304,

      321,  333,  298,  322,  338,  267,  904,    0,  376,  382,
      396,  331,  332,  376,  427,  382,  336,  212,  377,  389,
      398,  412,  306,  431,  364,  384,    0,  416,  436,  405,
      467,  453,  469,  473,    0,   79,  440,  474,  477,  488,
      485,  487,  501,  464,  480,  489,    0,  493,  522,  526,
      494,  870,  109,  531,  858,  538,  287,  885,  867,  542,
      546, 1342,  866,  458,  546,  550,  552,  554,  556,  557,
      862, 1342,  326,  360,  542,  549,  555,  550,  560,  544,
      453,  469,  591,  598,  577,  581,  583,  587,  608,  592,
      600,  601,  572,  606,  610,  180,  622,  614,  618,    0,

      652,  629, 1342,  630,  853,  542,  833,  810, 1342,    0,
      657,  663,  665,  673,  683,  694,  695,  649,  662,  706,
      700,  711,  746,  719,  726,  730,  734, 1342,  814,  715,
      756,  714,  751,  741,  740,  749,  748,  757,    0,  680,
      763,  769,    0,  764,  800,  774,  777,  353,  764,  796,
      803,  804,  807,  808,  809,  810,    0, 1342, 1342,  771,
      749,  733,  821,  844,  820,  847,  823,  850,  667, 1342,
      727,  822,  828,  849,  855,  860,  899,  869,  873,  877,
      882,  894,  880,  911,  922,  891,  875,    0, 1342,  901,
      927,  937,  948, 1342,  908,  942,  944,  952,  956,  957,

      958, 1342,  961,  733,  681,  662,  650,  982,  971,  993,
     1004, 1007, 1043,  968,  978, 1001, 1009, 1012, 1014,  917,
     1018,    0,  620, 1015,  500, 1026,  518, 1032, 1030, 1048,
      997, 1036, 1069, 1052, 1074, 1057, 1044, 1073, 1086, 1094,
      645,  614,  603, 1082, 1109, 1097, 1108, 1115, 1342, 1119,
      670,  587,  559,  544, 1342, 1342,  719,  862,  525, 1121,
     1126, 1132, 1127, 1138,  430,  413,  404,  400, 1342,  974,
     1342, 1342, 1142, 1342,  396,  380,  367,  361, 1342, 1342,
     1054, 1144, 1145, 1101, 1342,  297,  269,  432, 1342, 1342,
      907, 1147,  342,  192, 1342, 1342,  168, 1163, 1169, 1181,

     1193, 1205, 1216, 1228,  161, 1239, 1250, 1260, 1271,  147,
     1282,   63, 1290, 1295, 1307, 1314,   38, 1321, 1328
    } ;

static yyconst short int yy_def[420] =
    {   0,
      396,    1,  396,  396,  396,  396,  396,  397,  396,  396,
      398,  398,  398,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,  396,
      396,  399,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  400,  400,   45,   13,  396,   13,   13,
       13,   13,   13,   13,   13,   13,   13,  398,  401,  401,
       60,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   20,   13,   20,   13,   13,   66,   13,   13,  396,
      399,  396,  396,  396,  396,  402,  402,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  403,  403,

      403,  403,  403,  403,  403,   48,   48,    9,  404,  404,
      404,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,   20,   13,   13,  124,   13,   13,   13,
       45,   45,   45,  402,  405,  396,  406,  406,  406,  406,
      406,  406,  406,   13,   13,   13,  124,   13,  398,  398,
      124,  124,  124,  396,  396,  396,  402,  407,  396,  396,
      396,  396,  400,  403,  403,  403,  403,  403,  403,  403,
      400,  396,  400,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  401,  401,  111,  111,  111,  111,  111,  111,
      111,  111,  115,  111,  111,  189,  111,  111,   13,  124,

      408,   13,  396,   13,  396,  396,  409,  396,  396,  410,
      406,  406,  406,  406,  406,  406,  406,   13,   13,   45,
       45,   45,   45,  223,  223,  398,  396,  396,  407,  403,
      403,  403,  403,  403,  403,  115,  111,  111,  236,  111,
      111,  111,  236,  111,  404,  236,  236,  236,  411,  411,
      411,  411,  411,  411,  411,   13,  412,  396,  396,  409,
      413,  414,  406,  406,  406,  406,  406,  406,   13,  396,
      396,  403,  403,  403,  403,  403,  223,  277,  277,  403,
      396,  396,  403,  403,  403,  403,  111,  236,  396,  111,
      223,  291,  404,  396,  411,  411,  411,  411,  411,  411,

      411,  396,  415,  413,  416,  396,  414,  406,  406,  406,
      406,  406,  291,  403,  403,  403,  403,  403,  403,  396,
      396,  417,  396,  403,  396,  396,  396,  396,  403,  277,
      330,  411,  411,  411,  411,  411,  411,  396,  396,  415,
      396,  416,  396,  406,  406,  403,  403,  403,  396,  403,
      396,  396,  396,  418,  396,  396,  396,  396,  396,  411,
      411,  411,  411,  411,  396,  396,  396,  396,  396,  396,
      396,  396,  403,  396,  419,  396,  396,  418,  396,  396,
      396,  411,  411,  396,  396,  396,  419,  396,  396,  396,
      396,  396,  396,  396,  396,    0,  396,  396,  396,  396,

      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396
    } ;

static yyconst short int yy_nxt[1385] =
    {   0,
        4,    5,    6,    7,    7,    4,    8,    4,    4,    4,
        9,   10,    4,    4,    4,    4,    4,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   17,   21,   22,
       23,   24,   25,   17,   26,   27,   28,   17,   17,   29,
       12,   17,   31,   31,   33,   53,   34,   35,   47,   47,
      354,   47,   47,   36,   82,   37,   38,   44,   39,   45,
       46,   40,   41,   42,   83,   44,   43,   45,   46,   44,
       48,   45,   46,   31,   31,  303,   49,   47,   48,   54,
       47,   55,   48,   58,   56,   57,   50,   47,   47,   47,
       95,   47,   47,   66,   47,   98,   51,   71,  208,   52,

       59,   47,   60,   61,   47,   67,   73,   47,   47,   92,
       47,   47,   68,   72,   47,   47,   69,  130,   47,  208,
       62,   93,   63,   47,   96,   97,   47,   64,   74,   86,
       47,   47,   70,  157,   65,   76,   47,   75,   47,   47,
       74,   47,   74,  226,   44,   79,   77,   78,   47,   73,
       47,   47,  124,   47,   86,  125,   87,   87,   74,  262,
       47,  100,   47,   47,  101,   47,   47,   47,  126,   47,
       47,   47,  102,  207,   88,   47,   89,  103,   47,  128,
       32,   90,  104,   47,  151,  127,   47,   47,   91,  396,
       47,   46,   46,   47,  395,  129,  129,  131,   47,  132,

      133,   47,  174,   74,   47,   47,  100,   47,   47,  101,
       48,   47,   74,   74,   47,  246,  147,  102,   47,   47,
      144,   47,  103,  105,  145,   74,   47,  104,  106,   47,
      107,  107,   47,   47,  146,   47,   47,  108,   47,   47,
      174,  150,  129,  192,  109,  110,  111,  112,  110,  113,
      110,  114,  110,  115,  110,  116,  117,  118,  119,  110,
      110,  120,  121,  122,  110,  110,  123,  110,  110,   59,
      396,  396,   47,  134,  135,   47,  386,   47,  148,  149,
       47,  162,   47,  136,   47,  152,  138,   47,  396,  139,
      163,   47,  396,   47,   47,   47,  129,  140,   47,  374,

      162,   86,  141,   87,   87,  153,  162,  142,  396,  163,
       61,   61,  134,  135,  396,  163,   87,   87,  157,  168,
       95,   95,  136,  162,  162,  138,  193,  396,  139,  173,
      173,   95,  163,  163,  174,  162,  140,  174,  161,   95,
      162,  141,  143,   95,  163,  165,  142,   74,   74,  163,
      167,  394,   74,  169,  166,  393,  179,  180,   74,  174,
      181,   47,  174,  174,  174,   74,   74,  174,  377,  355,
       74,   95,   95,  191,  170,  174,   95,  171,  172,  173,
      173,  199,   95,  171,  172,  173,  173,  293,  174,   95,
       95,  174,   47,  388,   95,   47,  175,  171,  172,  173,

      173,  182,  189,  386,  174,  174,  176,  174,  174,  193,
      174,  193,   47,  174,  190,   47,  200,  174,  194,  201,
      174,  384,  204,  195,  177,  384,  174,  178,  183,  174,
      184,  184,  193,   47,  196,  197,   47,  198,  203,  386,
      174,  202,  209,  174,   47,  388,  210,   47,  185,  384,
      186,  163,   47,   74,   47,  187,  133,  133,  174,   47,
      162,  205,  188,  384,   47,  150,   47,   47,  131,  163,
      396,  396,  133,  133,  396,  205,  209,  205,  396,  209,
      210,  174,   74,  210,  241,  163,  206,  209,  163,  209,
      209,  210,   47,  210,  210,   47,  163,  174,  163,  163,

      240,  325,   99,  209,   99,  214,  215,  210,   47,  219,
      213,   47,  163,  357,  218,  212,   47,   47,  216,  327,
       47,   47,  129,  220,   47,  221,  222,  223,   47,  224,
      225,  358,   86,   74,   87,   87,   48,  217,  381,   86,
       48,   87,   87,   86,  258,   87,   87,   86,  162,   87,
       87,  377,  162,   95,  162,  206,  162,  163,  162,  162,
       95,  163,  236,  163,   95,  163,  376,  163,  163,  193,
      174,  232,  174,  174,  235,  174,  237,  174,  174,  238,
      174,  174,  230,  174,  240,   95,  174,  231,  174,  233,
      234,  174,  183,  174,  375,  174,  134,  135,  239,  396,

      174,  184,  184,  134,  135,  174,  136,  174,  174,  174,
      193,  174,  174,  136,  174,  174,  370,  193,  174,  193,
      174,  341,  355,  174,  242,  193,  193,  193,  243,  174,
      193,  174,  174,  323,  174,  244,  193,  245,  174,  174,
      247,  240,  174,  193,  193,  240,   47,  369,  193,   47,
      174,  256,  226,  174,  248,   46,   46,   47,   47,  209,
       47,   47,  306,  210,  270,  209,  129,  209,  163,  210,
      250,  210,  374,  251,  163,  209,  163,   47,  343,  210,
      269,  252,  289,  351,  163,  209,  253,  254,  341,  210,
       47,  255,  265,   47,  163,   47,  209,  209,   47,  263,

      210,  210,  264,  222,  222,  163,  163,  220,  174,  396,
      396,  174,  268,  271,  222,  222,  162,  162,  266,  271,
      396,  379,  225,  225,  271,  163,  163,  396,  267,  225,
      225,  277,  357,  278,  279,   86,  280,   87,   87,  396,
      271,   99,  162,  162,   48,  306,   99,  223,  283,  396,
      396,  163,  163,  162,  276,  304,   95,  281,  162,  282,
      282,  285,  163,  272,  273,  287,  294,  163,  272,  284,
      174,  193,  174,  259,  286,  163,  174,  174,  274,  174,
      290,  275,  272,  245,  174,  174,  272,  193,  174,  288,
      284,  174,  174,  240,  174,  174,  174,  174,  294,  174,

      174,  291,  172,  292,  292,  294,  294,  163,  174,  294,
      294,  294,  302,  193,  163,  163,  228,  261,  163,  163,
      163,  298,  209,  209,  162,  209,  210,  210,  299,  210,
      162,  163,  163,  313,  163,  259,  297,  296,   47,  313,
      301,   47,  308,  311,  300,  281,  209,  282,  282,  209,
      210,  162,  209,  210,  309,  163,  210,  162,  163,  257,
      163,  163,  162,  171,  380,  310,  313,  396,  314,  165,
      396,  313,  279,  279,  396,  358,  279,  279,  320,  162,
      321,  321,  162,  281,  312,   95,  310,  228,  163,  322,
      227,  163,   47,  162,  314,  323,  170,  282,  282,  314,

      277,  322,  163,  174,  319,  396,  174,  323,  391,  293,
      294,  324,  325,  162,  326,  326,  315,  316,  320,  163,
      393,  315,  163,  327,  162,  328,  328,  329,  291,  174,
      351,  317,  174,  163,  318,  315,  352,  240,  396,  315,
      292,  292,   95,   95,  294,  272,  294,  160,   99,  330,
      172,  331,  331,  163,  294,  163,   99,  353,  294,  294,
      294,   99,  338,  163,  339,  339,   99,  163,  163,  163,
      162,  334,   95,  209,  336,  159,  385,  210,  332,  313,
      349,  333,  163,  320,  209,  321,  321,  370,  210,  163,
       95,  335,  337,  163,  325,  209,  326,  326,  396,  210,

      331,  331,  344,  349,  163,  327,  209,  328,  328,  209,
      210,  162,  163,  210,  349,  163,  349,  356,  163,   95,
      163,  321,  321,  163,   95,  163,  163,  156,  350,  326,
      326,  351,  162,  359,  155,  328,  328,  352,  294,  357,
       95,  163,  165,  345,  396,  358,  294,  163,  154,  330,
      170,  350,   80,  350,  294,  163,  389,  360,  353,  294,
      346,  346,  137,  163,  364,  346,  315,  381,  163,   99,
      281,  294,  282,  282,  338,  347,  294,   99,  348,  346,
      163,   99,   99,  346,  371,  163,  361,   99,  210,  339,
      339,  363,  362,  163,  365,  338,  366,  339,  339,  372,

       95,  367,  391,  368,  392,  392,   95,  365,  163,  366,
      162,  209,  359,  362,  367,  210,  368,  372,   95,  163,
      163,  349,  320,  294,  321,  321,  163,  373,  294,  294,
      163,   94,  163,  325,  294,  326,  326,  163,  163,  327,
      294,  328,  328,  163,  372,   85,  390,  294,  359,  163,
      392,  392,   84,  163,  373,  163,  163,  382,   80,   30,
      393,   30,  396,  383,   47,  396,   47,  396,  396,  396,
      396,  396,   47,   47,  396,   47,   81,  396,   81,  396,
      396,   81,   99,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,   99,  137,  396,  396,  137,  137,  396,

      396,  396,  396,  396,  137,  137,  158,  396,  396,  158,
      396,  396,  396,  396,  396,  396,  396,  158,  164,  396,
      396,  396,  396,  164,  396,  164,  396,  396,  164,  174,
      174,  174,  396,  396,  396,  396,  396,  174,  396,  396,
      174,  211,  396,  396,  211,  396,  211,  396,  211,  396,
      396,  211,  229,  396,  396,  396,  396,  396,  396,  229,
      396,  396,  229,  249,  396,  396,  396,  396,  396,  396,
      396,  396,  249,  260,  396,  396,  396,  396,  396,  396,
      260,  396,  396,  260,  295,  396,  396,  396,  396,  295,
      396,  295,  396,  396,  295,  305,  396,  396,  396,  396,

      396,  396,  305,  307,  307,  396,  396,  307,  340,  396,
      340,  396,  396,  396,  396,  396,  340,  396,  396,  340,
      342,  396,  396,  342,  396,  396,  342,  378,  396,  396,
      378,  396,  396,  378,  387,  396,  396,  387,  396,  396,
      387,    3,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396
    } ;

static yyconst short int yy_chk[1385] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    7,    7,    9,   14,    9,    9,   14,   17,
      417,   14,   17,    9,   33,    9,    9,   11,    9,   11,
       11,    9,    9,    9,   33,   12,    9,   12,   12,   13,
       11,   13,   13,   31,   31,  412,   11,   15,   12,   15,
       15,   16,   13,   19,   16,   18,   11,   16,   18,   19,
       42,   18,   19,   21,   23,   42,   13,   23,  136,   13,

       20,   21,   20,   20,   21,   21,   25,   24,   47,   37,
       24,   47,   22,   24,   56,   25,   22,   56,   25,  136,
       20,   37,   20,   22,   41,   41,   22,   20,   26,   86,
       20,  153,   22,   86,   20,   27,   26,   26,   27,   26,
       28,   27,   29,  153,   44,   28,   27,   27,   28,   27,
       29,   28,   49,   29,   36,   51,   36,   36,   50,  410,
       49,   44,   51,   49,   44,   51,   50,   52,   52,   50,
       52,   77,   44,  405,   36,   53,   36,   44,   53,   54,
      397,   36,   44,   55,   77,   53,   55,   54,   36,   45,
       54,   45,   45,   57,  394,   55,   57,   58,   62,   58,

       58,   62,  196,   62,   63,   64,   45,   63,   64,   45,
       58,   65,   63,   64,   65,  196,   70,   45,   67,   70,
       65,   67,   45,   45,   68,   67,   73,   45,   48,   73,
       48,   48,   69,   68,   69,   69,   68,   48,   75,   76,
      118,   75,   76,  118,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   59,
      106,  106,   71,   59,   59,   71,  387,   72,   71,   72,
       74,   99,   74,   59,   72,   78,   59,   74,  157,   59,
       99,   72,  157,   79,   74,   78,   79,   59,   78,  386,

      103,   95,   59,   95,   95,   79,  100,   59,   60,  103,
       60,   60,   60,   60,   87,  100,   87,   87,   87,  103,
       96,   96,   60,  101,  104,   60,  123,  173,   60,  173,
      173,   96,  101,  104,  123,  102,   60,  123,   96,   96,
      105,   60,   60,   96,  102,  100,   60,   66,   66,  105,
      102,  393,   66,  104,  101,  393,  112,  113,   66,  112,
      113,   66,  112,  113,  117,   66,   66,  117,  378,  377,
       66,   92,   92,  117,  105,  248,   92,  109,  109,  109,
      109,  125,   92,  110,  110,  110,  110,  248,  174,   92,
       92,  174,  125,  376,   92,  125,  109,  111,  111,  111,

      111,  114,  116,  375,  114,  119,  109,  114,  119,  120,
      116,  119,  126,  116,  116,  126,  126,  120,  120,  128,
      120,  368,  130,  121,  111,  367,  121,  111,  115,  121,
      115,  115,  122,  130,  121,  121,  130,  122,  129,  388,
      122,  128,  137,  122,  128,  388,  137,  128,  115,  366,
      115,  137,  124,  124,  124,  115,  132,  132,  115,  124,
      164,  132,  115,  365,  129,  124,  124,  129,  131,  164,
      131,  131,  133,  133,  134,  131,  138,  133,  134,  139,
      138,  181,  144,  139,  181,  138,  134,  141,  139,  142,
      140,  141,  144,  142,  140,  144,  141,  182,  142,  140,

      182,  325,  131,  143,  133,  140,  141,  143,  145,  146,
      139,  145,  143,  325,  145,  138,  151,  146,  142,  327,
      146,  148,  148,  149,  148,  149,  149,  150,  151,  150,
      150,  327,  154,  151,  154,  154,  149,  143,  359,  156,
      150,  156,  156,  160,  206,  160,  160,  161,  165,  161,
      161,  354,  166,  154,  167,  206,  168,  165,  169,  170,
      156,  166,  175,  167,  160,  168,  353,  169,  170,  176,
      175,  167,  180,  175,  170,  180,  177,  176,  178,  178,
      176,  178,  165,  177,  180,  161,  177,  166,  179,  168,
      169,  179,  183,  193,  352,  193,  183,  183,  179,  184,

      193,  184,  184,  184,  184,  185,  183,  193,  185,  186,
      185,  187,  186,  184,  187,  188,  343,  186,  188,  187,
      190,  342,  323,  190,  188,  189,  189,  190,  191,  192,
      189,  191,  192,  323,  194,  192,  189,  194,  195,  189,
      197,  195,  198,  189,  189,  198,  199,  341,  189,  199,
      197,  202,  199,  197,  198,  201,  201,  202,  204,  211,
      202,  204,  307,  211,  219,  212,  204,  213,  211,  212,
      201,  213,  351,  201,  212,  214,  213,  218,  306,  214,
      218,  201,  240,  351,  214,  215,  201,  201,  305,  215,
      219,  201,  214,  219,  215,  269,  216,  217,  269,  212,

      216,  217,  213,  221,  221,  216,  217,  220,  240,  220,
      220,  240,  217,  221,  222,  222,  232,  230,  215,  220,
      224,  357,  224,  224,  222,  232,  230,  225,  216,  225,
      225,  226,  357,  226,  226,  227,  230,  227,  227,  304,
      271,  220,  235,  234,  226,  262,  222,  223,  232,  223,
      223,  235,  234,  233,  224,  261,  227,  231,  231,  231,
      231,  234,  233,  223,  223,  237,  249,  231,  223,  233,
      236,  236,  236,  260,  235,  249,  237,  236,  223,  237,
      241,  223,  223,  236,  236,  238,  223,  242,  238,  238,
      233,  241,  244,  244,  241,  244,  246,  242,  250,  247,

      242,  245,  245,  245,  245,  251,  252,  250,  246,  253,
      254,  255,  256,  246,  251,  252,  229,  208,  253,  254,
      255,  252,  265,  263,  272,  267,  265,  263,  253,  267,
      273,  265,  263,  272,  267,  207,  251,  250,  256,  273,
      255,  256,  263,  267,  254,  264,  264,  264,  264,  266,
      264,  274,  268,  266,  265,  264,  268,  275,  266,  205,
      274,  268,  276,  171,  358,  266,  275,  163,  274,  273,
      278,  276,  278,  278,  279,  358,  279,  279,  280,  280,
      280,  280,  283,  281,  268,  159,  266,  158,  280,  281,
      155,  283,  152,  286,  275,  281,  276,  282,  282,  276,

      277,  282,  286,  287,  278,  107,  287,  282,  391,  287,
      295,  283,  284,  284,  284,  284,  277,  277,  320,  295,
      391,  277,  284,  285,  285,  285,  285,  286,  291,  290,
      320,  277,  290,  285,  277,  277,  320,  290,  292,  277,
      292,  292,   98,   97,  296,  291,  297,   94,  291,  293,
      293,  293,  293,  296,  298,  297,  291,  320,  299,  300,
      301,  291,  303,  298,  303,  303,  291,  299,  300,  301,
      314,  298,   93,  309,  300,   91,  370,  309,  296,  314,
      315,  297,  309,  308,  308,  308,  308,  370,  308,  315,
       90,  299,  301,  308,  310,  310,  310,  310,  331,  310,

      331,  331,  309,  316,  310,  311,  311,  311,  311,  312,
      311,  317,  316,  312,  318,  311,  319,  324,  312,   89,
      317,  321,  321,  318,   88,  319,  324,   85,  317,  326,
      326,  321,  329,  329,   84,  328,  328,  321,  332,  326,
       83,  329,  316,  312,  313,  328,  337,  332,   82,  330,
      319,  318,   81,  319,  334,  337,  381,  332,  321,  336,
      313,  313,   61,  334,  337,  313,  330,  381,  336,  330,
      333,  333,  333,  333,  338,  313,  335,  330,  313,  313,
      333,   46,  330,  313,  344,  335,  334,  330,  344,  339,
      339,  336,  335,  344,  338,  340,  338,  340,  340,  346,

       43,  338,  384,  338,  384,  384,   40,  339,  346,  339,
      347,  345,  345,  335,  339,  345,  339,  348,   39,  347,
      345,  350,  360,  360,  360,  360,  348,  347,  361,  363,
      350,   38,  360,  362,  362,  362,  362,  361,  363,  364,
      364,  364,  364,  362,  373,   35,  382,  383,  383,  364,
      392,  392,   34,  373,  348,  382,  383,  361,   32,   30,
      392,    5,    3,  363,  398,    0,  398,    0,    0,    0,
        0,    0,  398,  398,    0,  398,  399,    0,  399,    0,
        0,  399,  400,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  400,  401,    0,    0,  401,  401,    0,

        0,    0,    0,    0,  401,  401,  402,    0,    0,  402,
        0,    0,    0,    0,    0,    0,    0,  402,  403,    0,
        0,    0,    0,  403,    0,  403,    0,    0,  403,  404,
      404,  404,    0,    0,    0,    0,    0,  404,    0,    0,
      404,  406,    0,    0,  406,    0,  406,    0,  406,    0,
        0,  406,  407,    0,    0,    0,    0,    0,    0,  407,
        0,    0,  407,  408,    0,    0,    0,    0,    0,    0,
        0,    0,  408,  409,    0,    0,    0,    0,    0,    0,
      409,    0,    0,  409,  411,    0,    0,    0,    0,  411,
        0,  411,    0,    0,  411,  413,    0,    0,    0,    0,

        0,    0,  413,  414,  414,    0,    0,  414,  415,    0,
      415,    0,    0,    0,    0,    0,  415,    0,    0,  415,
      416,    0,    0,  416,    0,    0,  416,  418,    0,    0,
      418,    0,    0,  418,  419,    0,    0,  419,    0,    0,
      419,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      396,  396,  396,  396
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "macroprocessor.l"
#define INITIAL 0
#line 2 "macroprocessor.l"
#include<stdio.h>
#include "y.tab.h"
#include "data_structures.h"
#line 806 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 14 "macroprocessor.l"

#line 959 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 397 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1342 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 15 "macroprocessor.l"
{return START;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "macroprocessor.l"
return END;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "macroprocessor.l"
return MACRO;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "macroprocessor.l"
return MEND;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 19 "macroprocessor.l"
return MACROPARAM;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 20 "macroprocessor.l"
return MACROPARAM;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 21 "macroprocessor.l"
return ORG;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 22 "macroprocessor.l"
return IF;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 23 "macroprocessor.l"
return ENDIF;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 24 "macroprocessor.l"
return CONCATPARAM;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 25 "macroprocessor.l"
return OPRTYPE1;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "macroprocessor.l"
return OPRTYPE2;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "macroprocessor.l"
return OPRTYPE3;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 28 "macroprocessor.l"
return OPRTYPE4;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 29 "macroprocessor.l"
{return REGOPR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 30 "macroprocessor.l"
{return REGOPR;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 31 "macroprocessor.l"
return TYPE1;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 32 "macroprocessor.l"
return REG;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 33 "macroprocessor.l"
return WS;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 34 "macroprocessor.l"
return RESERVE;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 35 "macroprocessor.l"
return EQU;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 36 "macroprocessor.l"
return BYTE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 37 "macroprocessor.l"
return WORD;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 38 "macroprocessor.l"
return LABEL;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 39 "macroprocessor.l"
{printf("mac : %s\n",yytext);return SMAC;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 40 "macroprocessor.l"
{return MACROCALL;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 41 "macroprocessor.l"
return MACROCALL;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 42 "macroprocessor.l"
return COM;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "macroprocessor.l"
return yytext[0];
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "macroprocessor.l"
ECHO;
	YY_BREAK
#line 1192 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 397 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 397 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 396);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 44 "macroprocessor.l"

int yywrap(){return 1;}

